// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bytszlrigwpdahrnxlxa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ5dHN6bHJpZ3dwZGFocm54bHhhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUzODY1MDcsImV4cCI6MjA3MDk2MjUwN30.-CZDGXFinr30N0q5y8PzlWCx2n9eopBWhgkQCtmwe3Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});